apiVersion: v1
kind: Pod
metadata:
  name: helloworld
spec:
  containers:
  - name: envars-test-container
    image: nginx
    env:
    - name: connectionstring
      valueFrom:
        secretKeyRef:
          name: sc-storagelinker-secret
          key: AZURE_STORAGEACCOUNT_CONNECTIONSTRING
   